### ISSUE TITLE
[feature request] modify exp

### ISSUE THREAD

**Issue by epheien** [NovFR/DoS-2-Savegame-Editor#11]
It's better it can modity exp of role.

**Comment by NovFR** [comment]
What do you mean ?

**Comment by epheien** [comment]
I means I can modify level 34 via modify experience to 999999999

**Comment by karlkeuler** [comment]
ja , i wanna modify level and exp too. My game has a bug when i got 36 level, and when i get some exp ,it will level up to 1 level..... How can fix that

**Comment by NovFR** [comment]
As far as I know, you can't change the level directly, it is based on your experience points.

If you really want to change your exp, you can use the **character's tree** (first entry in the **Advanced** menu):
* Open the **children** node
* Open **node[id=Stats]**
* Open **attribute[id=Experience]**
* Change the value to whatever you want

**Comment by karlkeuler** [comment]
> As far as I know, you can't change the level directly, it is based on your experience points.
> 
> If you really want to change your exp, you can use the **character's tree** (first entry in the **Advanced** menu):
> 
> * Open the **children** node
> * Open **node[id=Stats]**
> * Open **attribute[id=Experience]**
> * Change the value to whatever you want

ya, but it will make the level down....

I m thinking, can we change the level table, to decrease the exp between every level? Then with same exp we can get higher level...

I heard that this bug is come from the exp overflow. only 32-bit for max exp, or we can change that?

**Comment by NovFR** [comment]
I am not aware of a method to change the level table.

> I heard that this bug is come from the exp overflow. only 32-bit for max exp, or we can change that

I'm pretty sure we can't change that. The game expect a 32 bit value.

I don't know how to fix your problem, but to be honest I don't understand how you can reach such a high level.

**Comment by karlkeuler** [comment]
I m using other mod to get more monster and double them .... so i can reach such a high level....

**Comment by NovFR** [comment]
Added in 1.1.0.0.
