### ISSUE TITLE
Crash problem

### ISSUE THREAD

**Issue by Occam42** [NovFR/DoS-2-Savegame-Editor#12]
The game version I use is DE   without MOD
I used bugs in the game to get multiple permanent followers

When I use DoS-2-Savegame-Editor to load these archives with entourage, it will cause the EDitor to crash 
I did not find the error log of the editor

I used the translation software to translate the above paragraph 
 Hope to express clearly

thank you

**Comment by NovFR** [comment]
Can you upload your savegame ?

**Comment by Occam42** [comment]
> Can you upload your savegame ?

https://1drv.ms/u/s!Aiof_AHrdwXJhXsWNI1MvZmaEGhr?e=R6Ljhg

The archive before reaching arx is readable
After arriving at arx, it may be that the editor crashes due to reading the characters displayed as followers

**Comment by NovFR** [comment]
The editor crashes because some characters in your team have no attributes, it was not expected. I'm working on a fix.

**Comment by Occam42** [comment]
> The editor crashes because some characters in your team have no attributes, it was not expected. I'm working on a fix.

thanks a million!!


It is recommended that you learn how to turn various followers into permanent followers in the original game.
For example, after taking Alexander to arx city and using equipment to improve persuasion, you can use the built-in resurrection skills to resurrect non-hostile NPCs and have a very powerful aura.
![RD5~ 0SJRE1OH QVG }WPM8](https://user-images.githubusercontent.com/42971553/88929821-3941a500-d2ad-11ea-8832-f6dbfe382d0c.png)

**Comment by NovFR** [comment]
Should be fixed in latest version.
