### ISSUE TITLE
Add capability to add "AVATAR" tag to a character.

### ISSUE THREAD

**Issue by rheavr** [NovFR/DoS-2-Savegame-Editor#13]
DOS2 has a bug where if a player joins a multiplayer campaign later in the game that player is not considered a player character (avatar). I think this can be fixed by adding the avatar tag to that character.

**Comment by NovFR** [comment]
You can already add/modify any tag you want by modifying the Tags.txt file located in the Datas folder.

Just remove the minus sign before AVATAR if you want to be able to add that tag.

**Comment by rheavr** [comment]
Nice, thanks for the quick reply 👍
