### ISSUE TITLE
Possible to edit staff damage type?

### ISSUE THREAD

**Issue by Bogdanov89** [NovFR/DoS-2-Savegame-Editor#14]
I have purchased a staff that deals fire damage but i wanted to change it to physical damage (so my attacks and warfare does physical instead of fire).
However i have not found where i can do such a change in this editor.

Can you please explain how can i change staff damage from whatever element to physical?
Thank you.

**Comment by NovFR** [comment]
There is a permanent bonus called "Damage type" for weapons: category Others in the list. You can't modify the damage type directly but maybe if you create a "physical damage" type bonus, the game will use physical damage instead of fire damage for that weapon.

**Comment by Bogdanov89** [comment]
Thank you for replying.
I tried changing the damage type on several staffs and wands but it has not done anything when tested in game, all the edited items behaved as if i changed nothing.

I was hoping that perhaps when in editor selecting the "show tree" option for an item would have an option to change/choose the weapon damage type.
There even is a "attribute[id=DamageTypeOverwrite] line in children/nnode[id=stats] but i do not know what the numerical value and type lines affect...
Strangely they seem to be set to the same numbers regardless of what damage type an item originally has.

**Comment by NovFR** [comment]
You may try to set DamageTypeOverwrite value to 1. Otherwise, I don't know. I have no access to the game currently, so I can't make further research.

**Comment by Bogdanov89** [comment]
I did some simple testing of the "DamageTypeOverwrite" on several wands:

The Value line dictates what damage type it will be, with 0 being typeless and then going all the way up to 12 (or so) with various damage types (3 was physical, for example).
Some damage types are really weird and seem unfinished (like Chaos, for example) and may behave a bit strange, which could explain why they are not implemented for player use.

The Type line is by default set to 4 and this whole thing only works if it is left at 4... if you change it from 4 then bad things happen (ranging from DamageTypeOverwrite not working to crashing the game, failing to load and even failing to save in editor).

Do note that the particular DamageTypeOverwrite line does not change visual animations or what type of "terrain/puddle" wands spawn when attacking.
But as far as i could test the DamageTypeOverwrite line properly changes the damage type of the weapon and makes it properly scale with the applicable warfare/geomancer/whatever.

If someone has the time and skill to do more detailed testing that would be great.

**Comment by NovFR** [comment]
Sounds interesting. But I am not really sure it is worth the effort to make an UI to change that value, since your testing shows it is partially implemented ingame. Can be confusing for most people, I don't know.

The "Type" line indicates what sort of data is "Value". 4 means "Value is an Integer".
