### ISSUE TITLE
"Flaming Skin" skill in "Permanent Bonuses" under Pyromancer instead of Polymorph

### ISSUE THREAD

**Issue by zambospam** [NovFR/DoS-2-Savegame-Editor#15]
Pretty much as the title implies, when adding "Permanent Bonuses" to items there is _Icy Skin_, _Poisonous Skin_ and _Jellyfish Skin_ under the **Polymorph** category, but _Flaming Skin_ is instead under the **Pyromancer** category.

Not really a bug, more like a "consistency issue".

**Comment by NovFR** [comment]
Fixed, thank you ^^
