### ISSUE TITLE
[Feature Request] Option to grant passive statuses in "Permanent Bonuses"

### ISSUE THREAD

**Issue by zambospam** [NovFR/DoS-2-Savegame-Editor#16]
Is there a way to add **_Set_** statuses to equipment? 
For example a basic "Set Poisoned" or a more complex "Set Thick of the Fight" like in this unique item:

> ![image](https://user-images.githubusercontent.com/33596528/89534002-95984d80-d7f4-11ea-964f-972958b310f5.png) 

or "Set Clear-Minded": 

> ![image](https://user-images.githubusercontent.com/33596528/89534268-f4f65d80-d7f4-11ea-9470-7d621cedc299.png)

**Comment by NovFR** [comment]
Not currently. Do you see thoses bonuses in the editor ?

**Comment by zambospam** [comment]
I do not see those bonuses, I wish there was an option to add them as "Permanent Bonuses" hence the _Request_ in my title.
Do you think it's doable?

**Comment by NovFR** [comment]
If those bonuses are not in the savegame, there is little chance I can find how to add them, unfortunately.
