### ISSUE TITLE
[Feature Request] A "save as" function or a way to read savegame file from non-default locations

### ISSUE THREAD

**Issue by sws124** [NovFR/DoS-2-Savegame-Editor#17]
Due to my incompetence (probably some permission issues in my computer), I can't seem to save the savegame file in C drive using the savegame editor. I can, however, use the conversion tool to edit and save the file in D drive without problems.

So I am thinking, if there is a way to let the editor read a savegame file from other locations, like somewhere besides the default "C:\Users\user\Documents\Larian Studios\Divinity Original Sin 2 Definitive Edition\PlayerProfiles". Or maybe I can save the edited file to non-default locations.

That would be a great help since this savegame editor is much easier to use than the conversion tool.

**Comment by NovFR** [comment]
Working on it. Can't say when this will be ready, however.

**Comment by sws124** [comment]
Thank you so much.

**Comment by NovFR** [comment]
Done. Hope the changes will fix most permission issues.

**Comment by sws124** [comment]
It works. Thanks for your effort.
