### ISSUE TITLE
Missing Skills you can't add as Permanent Bonuses

### ISSUE THREAD

**Issue by zambospam** [NovFR/DoS-2-Savegame-Editor#18]
There are currently missing some skills you can't add as permanent bonus on items.

(Available with _Pet Power_ gift bag) **Cursed Blood Infusion**, obtained by crafting: 
Source Summoner book + Necro book
Summoner book + Source Necro book

(Available with _Pet Power_ gift bag) **Cursed Oil Infusion**, obtained by crafting:
Source Summoner book + Geo book + Oil barrel
Summoner book + Source Geo book + Oil barrel
Source Summoner + Source Geo Book + Oil barrel

Summon Dragonling (_https://divinityoriginalsin2.wiki.fextralife.com/Summon+Dragonling_)

Summon Poison Slug (_https://divinityoriginalsin2.wiki.fextralife.com/Summon+Poison+Slug_)

**Comment by NovFR** [comment]
I added Cursed Blood Infusion and Cursed Oil Infusion, but I wasn't able to find Summon Dragonling and Summon Poison Slug in game files.

**Comment by NovFR** [comment]
Finally found those little fellas (thanks to #30) Will be added in later release.
