### ISSUE TITLE
Failed to convert resource: 'Teleport' is an unexpected token. Expecting white space. Line 285, position 56.

### ISSUE THREAD

**Issue by xecus922** [NovFR/DoS-2-Savegame-Editor#22]
Getting this error while trying to save the editor changes and converting. Hope you can help me figure this out, I just got done making so many changes, don't want to close the editor and lose all that.

I am using quite a bit of mods, about 50 of them. I think one or two of them have something to do with teleporting so I'll try disabling them see what happens.

You can add me on discord for faster communication: steve_#5129 or if you have a discord server I'll join that.

I've added my save file for you below.

[Save Editor Test Reapers Coast - 454h21m (2).zip](https://github.com/NovFR/DoS-2-Savegame-Editor/files/5480351/Save.Editor.Test.Reapers.Coast.-.454h21m.2.zip)

**Comment by NovFR** [comment]
I added you on Discord. I don't really know where the problem is actually but upgrading to the latest LSLib version seems to fix it.

**Comment by xecus922** [comment]
Sorry wrong discord I gave you, it's steve_#5129

Trying to figure out how to install LSLib, can't find the damn download button, I'm not too familiar with LSLib -.-

**Comment by NovFR** [comment]
The editor needs to be updated in order to use the new LSLib version anyway.

**Comment by xecus922** [comment]
Yeah that fixed it.
