### ISSUE TITLE
Afraid of modifying values because the save editor will randomly crash afterwards

### ISSUE THREAD

**Issue by xecus922** [NovFR/DoS-2-Savegame-Editor#23]
I just had to post about this because it's just bothering me too much, I don't like being afraid of using a program. So your save editor is very useful to cut down on farm time for certain items, for crafting. But one serious issue with the save editor is that it will randomly crash after modifying a value. Many times I've modified the values for maybe 50+ items then after spending all that time modifying so many items one by one the save editor just decides to crash. I have to worry about this happening every time I open the save editor and it's very demoralizing, just makes me depressed using the save editor because I know it's going to crash eventually after modifying a value and I don't know when.

**Comment by NovFR** [comment]
I'm aware of this problem, but I can't say when it will be fixed since, like you said, it is relatively rare and random. If you have more details, it may help. In the meantime, save more often.

**Comment by xecus922** [comment]
Wait no, it's not rare, it will happen almost every time I use save editor IF I'm clicking okay with my mouse after I enter the modified value (like 99 for example then click ok with the mouse). It will just give up and crash after clicking okay (with mouse) after maybe ~20 value changes. It seems to not happen much at all if I confirm the modified values with th enter key on my keyboard strangely enough.

And you say save more often....man it takes like around 5-10 minutes just to do one save. That makes me NOT want to save often because I know I'm going to wait a very long time just for one save. Saves shouldn't be taking 5-10 minutes in a simple save editor, it shouldn't take that long to save in anything anywhere period.

Well at least you're aware of this.

**Comment by NovFR** [comment]
Can you send me your savegame ? What value are you modifying ? The amount ?

I made few tests and so far, no crash.

**Comment by xecus922** [comment]
[Cullwoods Mill - 679h11m.zip](https://github.com/NovFR/DoS-2-Savegame-Editor/files/5574829/Cullwoods.Mill.-.679h11m.zip)

I'm simply modifying the only value available for things like arrows, potions, etc Value is 99

This is all I do: Right click item I want to modify > Left click on 'Modify' > CTRL + V to add 99 into the 'Amount' field > Left click on 'OK'

That's it. And eventually after doing this to around ~20 items or so, it just crashes a few seconds after clicking 'OK'. I just now did it again on my very first try right now.

**Comment by xecus922** [comment]
I think the cause of this bug may be related to either how many different items are modified at one time or the amount of units modified per item in total, like a 'data overflow', as if there is a limit to how many item modifications can be made before the save editor just gives up and crashes. It's looking like somewhere around 50-75 modified items causes it to crash but I have to watch more closely to know for sure.

**Comment by NovFR** [comment]
Fixed in 1.1.0.0.
