### ISSUE TITLE
Remove avatar from character

### ISSUE THREAD

**Issue by victor-priceputu** [NovFR/DoS-2-Savegame-Editor#24]
This is a question: is there a way to make a character not be an avatar anymore? or just kick it out of the party completly?

We have a friend that dropped out of the session some time into the champaing and for obviouos story reasons we want to not have his character an avatar but a normal NPC type.

**Comment by NovFR** [comment]
Perhaps by removing the Avatar tag from this character. But I can't guarantee that it does anything.

If you want to test this, you will have to modify the Tags.txt file in the Datas directory, and remove the - in front of -AVATAR.
