### ISSUE TITLE
[feature request] editing character status

### ISSUE THREAD

**Issue by barfpony** [NovFR/DoS-2-Savegame-Editor#28]
Would it be possible to integrate a character status editor?  I was recently resurrecting a character, and while I could edit their vitality, magic armor, and physical armor using the character tree editor (maybe this could be a slider in the main window... :D), I couldn't remove their "DYING" status.  I had to manually unpack the file, and remove the nodes (StatusMeta and STATUS), since you can't remove nodes in GlEd.  The .lsf file I ended up creating made DoS2 crash, but reopening it in GlEd, then resaving it and letting it do the conversion fixed it.

All that would be required for the editor to change status would be editing the following on a character's tree:

children -> note[id=StatusManager] -> children -> node[id=StatusMeta]
and the corresponding
children -> note[id=StatusManager] -> children -> node[id=STATUS]

You can double check that they refer to the same status by checking each one's  "value" in attribute[id=ID].

This would allow removing burning, necrofire, dying, etc. without having to manually edit the file.

Thanks for making GlEd, it's really useful.

**Comment by NovFR** [comment]
Normally, you can remove a node or an attribute by hitting the **Del** key.

For the status editor, I'll see what I can do. Can take some time since I'm not very active at the moment.

**Comment by barfpony** [comment]
Ah, you're right, I didn't figure that out.  Thanks!  Your work is appreciated.

**Comment by NovFR** [comment]
I made some tests and it appears that removing the DYING status from the character is not enough to really revive it, even if you change the vitality amount. The character is "alive" but invulnerable and can't use any skills.

I'm therefore not sure it is a good idea to make changes in the StatusManager.

**Comment by qiuyang1008** [comment]
NPCs Resurrected by  the skill Resurrect of Alexandar are "alive" but can't be communicated any more.
There should be more than one variable in the Status or anywhere.

**Comment by NovFR** [comment]
I'll keep the request in mind, until I found a way to edit status without breaking anything.
