### ISSUE TITLE
[Question] How do I remove "stolen" flag from item?

### ISSUE THREAD

**Issue by Fatmice** [NovFR/DoS-2-Savegame-Editor#33]

**Comment by NovFR** [comment]
In item's tree:
1. Search for **attribute[id=owner]**, copy the value.
2. Then, find **attribute[id=OriginalOwnerCharacter]**, replace its value by the one above.

The stolen flag should be removed.

**Comment by Fatmice** [comment]
Just like that.  Thank you.
