### ISSUE TITLE
Issue when open application

### ISSUE THREAD

**Issue by NuclleaR** [NovFR/DoS-2-Savegame-Editor#5]
When I open App second time I faced with issue "Can't translate shortcut `Ctrl + O`"

**Comment by NovFR** [comment]
If you delete the file GlEd.config in the Prefs folder, does the issue persist ?
Actually, I see no reason why it worked the first time and not the second.

**Comment by N-Kata** [comment]
have totally the same issue
sometimes uninstallltion of DOS2SE helps, sometimes database programm, sometimes i need to restart my PC
I cant find the pattern

**Comment by Stellar-Daniel2** [comment]
Found something like a solution.
In "prefs" folder i delete Gied.config that weighs 0 kb(Dont touch other same named config). After that i creating a new one. But I need to do this every time I restart my computer but it works.
Also, when you open the "prefs" after installation there is no config so i just created a new one and it start working.

**Comment by xpyy** [comment]
I reproduced the bug. The app opens fine if my keyboard input is English, and crashes if it's Russian.

**Comment by NovFR** [comment]
> 
> 
> I reproduced the bug. The app opens fine if my keyboard input is English, and crashes if it's Russian.

I haven't tested yet, but I think you find the cause of the issue. The program should fail to correctly initialize shortcuts in non-latin keyboard layouts.

I'll try to find a workound.

**Comment by NovFR** [comment]
I think this issue is fixed. Open a new issue if it is not the case ^^
