### ISSUE TITLE
I'm dumb

### ISSUE THREAD

**Issue by xCarloC** [NovFR/DoS-2-Savegame-Editor#6]
Sorry I really can't understood how to open this editor. Can you show or write the step?

**Comment by NovFR** [comment]
Sure, it is pretty simple. I created a release so you just have to download the GlEd.zip archive and unpack it whenever you want (better to choose a destination where you have write access since it saves config files in the Prefs folder), then run GlEd.exe to open the editor.

**Comment by xCarloC** [comment]
Thanks, i found yesterday. Sorry for this tread.
