### ISSUE TITLE
Feature Request: Make attributes editable

### ISSUE THREAD

**Issue by PersonalProxy** [NovFR/DoS-2-Savegame-Editor#8]
Hello, thanks for this editor; it's been a life-saver.
I was wondering why the attributes cannot be edited directly from the pane where they are displayed once a save game is loaded?
I am not a programmer, so I couldn't being to conceive what would be needed to facilitate this functionality in the GUI... but I did do a bit of the legwork if you're interested.

---
It's _(relatively)_ easy to open the **Character Tree** and navigate to the section where the attributes are stored and modify their values. Currently, can be done by pressing **CTRL+T** and navigating to:

```javascript
children
  node[id=PlayerUpgrade]
    children
      node[id=Attributes]
        attribute[id=Object] // There are 6 of these listed, one for each base attribute.
          value="10"        // The number here will vary, dependant on your characters current actual stat.
```
Or, and alternate view if it's easier to understand:
```javascript
children | node[id=PlayerUpgrade] | children | node[id=Attributes] | attribute[id=Object] | value="10"
```
Under `attribute[id=Object]` you'll see three lines:
```javascript
id="Object" // Don't know what this does.
value="X"  // Changing this value, changes the state once saved.
type="4"  // Don't know what this does.
```
Editing **value="X"** to whatever you want the stat to be.
Note: **"X"** will be a number, whatever your character currently has for that attriute, e.g. 10, 16, 20, whatever.

--- 
The first 6 entries _(all named **`node[id=Attributes]`**)_ listed under
```javascript
children | node[id=PlayerUpgrade] | children | 
```
 are _(in order)_:

- Strength
- Finesse
- Intelligence
- Constitution
- Memory
- Wits

**E.g.**  If you want your **Strength** stat at 20, you'll go to the first **`node[id=Attributes]`** in the list and edit **`value="X"`** to 20.
If you want your **Memory** stat at 18 you'll go to the 5th **`node[id=Attributes]`* down, and edit **`value="X"`** to 18.

So, anyone wanting to know the easiest method _(that I have found)_ to alter attributes, there you have it.
If we could work this into the GUI of the Save Editor, that would be wonderful.

**Comment by NovFR** [comment]
Hello, it is already possible to edit attributes by clicking the icon next to the value of each attribute.
![Atttributes](https://user-images.githubusercontent.com/50532103/85537069-ede40900-b613-11ea-8196-ebcb110e4d3a.jpg)

Maybe the icons are not visible depending on the OS colors/theme. I don't know how the UI looks in other systems than mine.

**Comment by PersonalProxy** [comment]
Well, I feel like a complete dope.
You're absolutely correct, it was my Windows theme making the icons not visible.

Thanks very much!
