### ISSUE TITLE
Editeur 

### ISSUE THREAD

**Issue by DrVoodka** [NovFR/DoS-2-Savegame-Editor#9]
Bonjour 

a chaque fois que j'edit ma qauvegarde il n'y a rien qui se passe une fois en jeu par exemple suite a un bug je ne peut pas avoir le baiser de l'arraigner je me l'ajoute avec le save editor je sauvegarde mais une fois IG il n'y est pas 

Peux tu m'aider ?

**Comment by DrVoodka** [comment]
Après rectification je viens de voir qu'il s'ajoute mais n'est il pas possible d'avoir les autres stats du baiser de l'arraigner ?

**Comment by NovFR** [comment]
Salut !

Il faudrait que je procède à des vérifications en jeu mais je ne peux pas actuellement. Il y a apparemment plusieurs versions de ce talent qui dépendent des choix effectués durant la quête. Par conséquent, il est possible qu'activer une version de ce talent qui ne correspond pas à ces choix ne produise aucun effet.

Je vais essayer de voir ça dès que possible, mais pour le moment je n'ai aucune solution à te proposer.

**Comment by DrVoodka** [comment]
Ça marche je te remercie je me vois obligé de recommencer ma partie dans tous les cas suite a un bug qui va me bloque plus tard mdr
